name: excel_helper_app
description: A simple Flutter app to manage daily lists and export to Excel.
version: 0.1.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  excel: ^2.0.0
  path_provider: ^2.0.0
  share_plus: ^8.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.0

dependency_overrides:
  share_plus: ^8.0.0

flutter:
  uses-material-design: true
